<?php
use Illuminate\Database\Seeder;
class ApartmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       \Illuminate\Support\Facades\DB::table('apartments')->insert([
            [
                'name' => 'Chung cu Cua Thao',
                'address' => '220 my dinh',
                'price' => 10000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 1',
                'address' => '221 my dinh',
                'price' => 11000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 2',
                'address' => '222 my dinh',
                'price' => 12000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 3',
                'address' => '223 my dinh',
                'price' => 13000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 4',
                'address' => '224 my dinh',
                'price' => 14000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 5',
                'address' => '225 my dinh',
                'price' => 15000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 6',
                'address' => '226 my dinh',
                'price' => 16000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 7',
                'address' => '227 my dinh',
                'price' => 17000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 8',
                'address' => '228 my dinh',
                'price' => 18000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 9',
                'address' => '229 my dinh',
                'price' => 19000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 10',
                'address' => '230 my dinh',
                'price' => 20000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 11',
                'address' => '231 my dinh',
                'price' => 21000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 12',
                'address' => '232 my dinh',
                'price' => 22000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 13',
                'address' => '233 my dinh',
                'price' => 23000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 14',
                'address' => '234 my dinh',
                'price' => 24000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 15',
                'address' => '235 my dinh',
                'price' => 25000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 16',
                'address' => '236 my dinh',
                'price' => 26000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 17',
                'address' => '237 my dinh',
                'price' => 27000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 18',
                'address' => '238 my dinh',
                'price' => 28000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chung cu Cua Thao 19',
                'address' => '239 my dinh',
                'price' => 29000,
                'desciption' => "dang ha gia",
                'url_image' => "https://znews-photo-td.zadn.vn/w660/Uploaded/kbunac2/2018_04_03/Carina.jpg",
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ]);

    }
}
